### ISSUE TITLE
Parameterize webhook related environment variables

### ISSUE THREAD

**Issue by ildukm** [iplabs/terraform-kubernetes-aws-node-termination-handler#6]
Hi, it seems that there's no way to set `WEBHOOK_*` environment variables.

It would be nice to be supported.

Thank you.

**Comment by headcr4sh** [comment]
Hi @ildukm, thanks for the feature request.
I have just released v3.0.0 of the module which adds a bunch of of input variables that can now be used to manage the webhook configuration. I haven't tested the configuration options, so your feedback is appreciated.
